services:
  db:
    image: postgres:15
    container_name: g-postgres-db
    environment:
      POSTGRES_DB: gastosdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  backend:
    build: ./backend/ControleGastos.Api
    container_name: g-backend-api
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=gastosdb;Username=user;Password=password
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: g-frontend-web
    ports:
      - "3000:3000"
    depends_on:
      - backend